#ifndef Enum_h__
#define Enum_h__

enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };

enum FOCUSID { FOCUSID_NONE, FOCUSID_MAPTOOL, FOCUSID_NAVITOOL, FOCUSID_CAMERATOOL, FOCUSID_LISTTOOL, FOCUSID_DIRECTIONTOOL, FOCUSID_END };

#endif // Enum_h__
