#ifndef Macro_h__
#define Macro_h__

//화면 크기
#define FORM_MAIN_WIDTH			WINCX
#define FORM_MAIN_HEIGHT		WINCY

#define FORM_BOTTOM_WIDTH		FORM_MAIN_WIDTH
#define FORM_BOTTOM_HEIGHT		200

#define FORM_RIGHT_WIDTH		300
#define FORM_RIGHT_HEIGHT		FORM_MAIN_HEIGHT + FORM_BOTTOM_HEIGHT

#define FORM_BORDER				17

#define FORM_WIDTH				FORM_MAIN_WIDTH + FORM_RIGHT_WIDTH + FORM_BORDER
#define FORM_HEIGHT				FORM_MAIN_HEIGHT + FORM_BOTTOM_HEIGHT + FORM_BORDER

#endif // Macro_h__
